image: docker:stable

services:
    - docker:stable-dind

variables:
    REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    OS: "${CI_COMMIT_REF_NAME}"

before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

stages:
    - cuda
    - cudnn

.cuda_template: &cuda_definition
    stage: cuda
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker pull "${REPOSITORY}:${VERSION}-runtime-${OS}" || true
    - docker build --network=host --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   "${VERSION}/runtime"
    - docker pull "${REPOSITORY}:${VERSION}-devel-${OS}" || true
    - docker build --network=host -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${VERSION}/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:latest";
      fi
    - docker push "${REPOSITORY}"

.cuda_base_template: &cuda_base_definition
    stage: cuda
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker pull "${REPOSITORY}:${VERSION}-base-${OS}" || true
    - docker build --network=host --pull -t "${REPOSITORY}:${VERSION}-base-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-base-${OS}"
                   "${VERSION}/base"
    - docker pull "${REPOSITORY}:${VERSION}-runtime-${OS}" || true
    - docker build --network=host -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${VERSION}/runtime"
    - docker pull "${REPOSITORY}:${VERSION}-devel-${OS}" || true
    - docker build --network=host -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${VERSION}/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-base-${OS}" "${REPOSITORY}:${VERSION}-base";
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:latest";
      fi
    - docker push "${REPOSITORY}"

.cudnn_template: &cudnn_definition
    stage: cudnn
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - CUDA_VERSION="${CI_JOB_NAME:1:3}"
    - CUDNN_VERSION="${CI_JOB_NAME:5}"
    - docker pull "${REPOSITORY}:${VERSION}-runtime-${OS}" || true
    - docker build --network=host --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/runtime/${CUDNN_VERSION}"
    - docker pull "${REPOSITORY}:${VERSION}-devel-${OS}" || true
    - docker build --network=host --pull -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --cache-from "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/devel/${CUDNN_VERSION}"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - docker push "${REPOSITORY}"

v8.0:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_definition

v8.0-cudnn5:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v8.0-cudnn6:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v8.0-cudnn7:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v9.0:
    variables:
        NO_OS_SUFFIX: "true"
        LATEST: "true"
    <<: *cuda_base_definition

v9.0-cudnn7:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v9.1:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_base_definition

v9.1-cudnn7:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v9.2:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_base_definition

v9.2-cudnn7:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition
