image: docker

services:
    - docker:dind

variables:
    REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    OS: "${CI_COMMIT_REF_NAME}"

before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

stages:
    - cuda
    - cudnn

.cuda_template: &cuda_definition
    stage: cuda
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --label "com.nvidia.build.ref=${CI_COMMIT_SHA}"
                   --label "com.nvidia.build.id=${CI_JOB_ID}" "${VERSION}/runtime"
    - docker build -t "${REPOSITORY}:${VERSION}-devel-${OS}" "${VERSION}/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:latest";
      fi
    - docker push "${REPOSITORY}"

.cudnn_template: &cudnn_definition
    stage: cudnn
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - CUDA_VERSION="${CI_JOB_NAME:1:3}"
    - CUDNN_VERSION="${CI_JOB_NAME:5}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}" "${CUDA_VERSION}/runtime/${CUDNN_VERSION}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-devel-${OS}" "${CUDA_VERSION}/devel/${CUDNN_VERSION}"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - docker push "${REPOSITORY}"

v7.5:
    <<: *cuda_definition

v7.5-cudnn5:
    <<: *cudnn_definition

v8.0:
    <<: *cuda_definition

v8.0-cudnn5:
    <<: *cudnn_definition
